### ISSUE TITLE
Custom Coupon

### ISSUE THREAD

**Issue by GiannisRallis** [AmplifyPlugins/subscriber-discounts-for-woocommerce#3]
Hello thank you for the plugin works grate. I want to make a custom coupon code but the function.php code you have provide not work as i expected. It creates a prefix word+random letters. I want to send the exact word how to do that with function.php?

**Comment by ScottDeLuzio** [comment]
@GiannisRallis in the example code provided in the plugin documentation, I intentionally left the random letters after the prefix word. The reason why is because if you only return the exact word, it will return that same word as the discount code for every user. WooCommerce doesn't need dozens of the same coupon code to work. Actually when you manually try to create multiple coupons with the same code, WooCommerce gives this warning message:
![image](https://user-images.githubusercontent.com/10899897/116450717-79b85a00-a810-11eb-9ace-2bc1552291e0.png)

In your case, I don't think you need this plugin. I would suggest that you create one coupon code manually with either a far out or no expiration date. Then use the built-in "welcome email" sequence in your email provider (i.e. Mailchimp or Active Campaign) to send them the coupon code after they subscribe.

If you really want to use this plugin with it returning the same exact word as the coupon code each time you would do it like this:
```
function example_custom_discount_code( $discount, $email_address ){
    // Add your company name as a prefix to the discount code:
    $new_code = 'MyCompanyName';
    return $new_code;
}
add_filter( 'sdwoo_discount_code', 'example_custom_discount_code', 10, 2 );
```

Although, I really don't recommend this method.

**Comment by GiannisRallis** [comment]
Thank you very much for such fast response. You are right i have to discuss with my client for that. Thank you for the suggestion.
